import{a as v,S as I,i as a}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const P="44783480-725b805b80ef605c474d620ee";async function g(r,t,n){const s=`https://pixabay.com/api/?key=${P}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${n}&page=${t}`;try{const e=await v.get(s);if(e.status!==200)throw new Error("Network response was not ok");return e.data}catch(e){throw console.error("Error fetching images:",e),e}}let f;function $(){f=new I(".gallery a")}function p(){f&&f.refresh()}function b(r,t=!1){const n=document.getElementById("gallery"),s=r.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}">
        <div class="info">
          <p>Likes: <span class="number">${e.likes}</span></p>
          <p>Views: <span class="number">${e.views}</span></p>
          <p>Comments: <span class="number">${e.comments}</span></p>
          <p>Downloads: <span class="number">${e.downloads}</span></p>
        </div>
      </a>
    `).join("");t?n.insertAdjacentHTML("beforeend",s):n.innerHTML=s}const B=document.getElementById("searchForm"),y=document.getElementById("search-input"),E=document.querySelector(".loader"),m=document.getElementById("gallery"),d=document.getElementById("loadMoreBtn"),l=15;let i=1,c="",h=0;$();B.addEventListener("submit",async r=>{if(r.preventDefault(),c=y.value.trim(),!c){a.error({title:"Error",message:"Please enter a search query."});return}i=1,m.innerHTML="",d.style.display="none";try{w();const t=await g(c,i,l);if(h=t.totalHits,t.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}b(t.hits),t.hits.length>0&&i*l<h?d.style.display="block":t.hits.length<l&&a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),y.value="",p()}catch(t){console.error("Error searching images:",t),a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{L()}});d.addEventListener("click",async()=>{i+=1;try{w();const r=await g(c,i,l);b(r.hits,!0),i*l>=h&&(d.style.display="none",a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),p(),x()}catch(r){console.error("Error loading more images:",r),a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{L()}});function w(){E.style.display="block"}function L(){E.style.display="none"}function x(){const r=m.firstElementChild?m.firstElementChild.getBoundingClientRect().height:0;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
