import{a as E,S as v,i as l}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const I="44783480-725b805b80ef605c474d620ee";async function p(r,t){const n=`https://pixabay.com/api/?key=${I}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`;try{const o=await E.get(n);if(o.status!==200)throw new Error("Network response was not ok");return o.data}catch(o){throw console.error("Error fetching images:",o),o}}let u;function $(){u=new v(".gallery a")}function y(){u&&u.refresh()}function g(r,t=!1){const n=document.getElementById("gallery"),o=r.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}">
        <div class="info">
          <p>Likes: <span class="number">${e.likes}</span></p>
          <p>Views: <span class="number">${e.views}</span></p>
          <p>Comments: <span class="number">${e.comments}</span></p>
          <p>Downloads: <span class="number">${e.downloads}</span></p>
        </div>
      </a>
    `).join("");t?n.insertAdjacentHTML("beforeend",o):n.innerHTML=o}const B=document.getElementById("searchForm"),m=document.getElementById("search-input"),h=document.querySelector(".loader"),f=document.getElementById("gallery"),c=document.getElementById("loadMoreBtn");let a=1,i="",b=0;$();B.addEventListener("submit",async r=>{if(r.preventDefault(),i=m.value.trim(),!i){l.error({title:"Error",message:"Please enter a search query."});return}a=1,f.innerHTML="",c.style.display="none";try{L();const t=await p(i,a);b=t.totalHits,g(t.hits),t.hits.length>0&&(c.style.display="block"),m.value="",y()}catch(t){console.error("Error searching images:",t),l.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{w()}});c.addEventListener("click",async()=>{a+=1;try{L();const r=await p(i,a);g(r.hits,!0),a*15>=b&&(c.style.display="none",l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),y(),P()}catch(r){console.error("Error loading more images:",r),l.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{w()}});function L(){h.style.display="block",f.innerHTML=""}function w(){h.style.display="none"}function P(){const{height:r}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
